### ISSUE TITLE
Add an option to simply dump the steps to be run

### ISSUE THREAD

**Issue by autarch** [maxmind/Stepford#24]
Some sort of dry run type thing. We'd like to see the name of each step to be run, with a clear indication of dependencies and paralellism.

It'd be nice to include a simple `stepford` CLI command that can do this for us (and can later be expanded to do other stuff, perhaps?)

**Comment by jjatria** [comment]
I've been assigned this distribution for this month's Pull Request Challenge, and I was wondering what the state of this issue is. Would the maintainers still like for this to be implemented? And if so, are there any places where this should go?

The original issue mentions "a simple `stepford` CLI command", but I cannot find a `stepford` application where that command could be implemented.

Alternatively, if there are any other aspects that you think I could look into, I'd be happy to help.

Cheers!

**Comment by oalders** [comment]
@jjatria thanks for getting in touch about this!  The SYNOPSIS of the module has a very basic sample application you could look at https://metacpan.org/pod/Stepford#SYNOPSIS

We could also start with just dumping the graph and exiting rather than pretty printing all of the steps etc.

If you'd rather try a different ticket, #23 is trivial.  Also #25 and #31 might not be bad.  We're happy to help with any questions you may have.

**Comment by jjatria** [comment]
So I guess this should go in `Stepford::Runner`, as an option to `run`?

It could also be a separate method, but that seems noisy to me. What would you prefer as an interface?

1. `Stepford::Runner->run( %options, dry_run => 1);`

2. `Stepford::Runner->dry_run( %options );`

3. Both

> We could also start with just dumping the graph and exiting rather than pretty printing all of the steps etc.

Sure. I'll look into the actual dumping a bit later.

**Comment by oalders** [comment]
@jjatria #1 looks like a nice, clean way to go about it.

**Comment by oalders** [comment]
Closing as this was done in #35
