### ISSUE TITLE
Switch to Type::Tiny and Path::Tiny?

### ISSUE THREAD

**Issue by jjatria** [maxmind/Stepford#36]
I noticed that `Stepford` uses `Path::Class` and `Moosex::Types` for its type constraints and validation (such as in `Stepford::Runner`).

Would there be any interest in switching to `Type::Tiny` and `Path::Tiny`? The latter seems to have [some optimisations](http://www.dagolden.com/index.php/1838/goodbye-path-class-hello-path-tiny/), and I think its interface is much easier to use. But if the goal is for `Stepford` to work under all the obscure platforms that are supported by `Path::Class`, and not by the majority that is covered by `Path::Tiny`, then the switch would not be a good idea.

Likewise, the types used by `Type::Tiny` are in my opinion more versatile: not only can the same library (`Stepford::Types`) be used with `Moo`, `Moose`, and `Mouse`, but they can be used for [efficiently validating almost anything (including method calls)](http://blogs.perl.org/users/toby_inkster/2013/05/typetiny---not-just-for-attributes.html), and they are editable in place (so if you want to, say,  enable coercions from A to B in this one particular case, that is easily achievable).

I've looked a little bit into this, and I've managed to get [a branch in my local fork](https://github.com/jjatria/Stepford/tree/type-library) to pass the tests in `t/`. But before I spend too much time on getting the author tests to pass (I still have some dirty namespaces), I thought I'd ask if this would be a welcome change.

**Comment by oalders** [comment]
Internally we're already using `Path::Tiny`, so I would think it's fine to make that switch.  Normally we'd also use `Type::Tiny` for something we're releasing to CPAN, so I'm not sure why we didn't do that in this case.  There may have been concerns about `Type::Tiny`'s maintenance.  @oschwald thoughts?

**Comment by oschwald** [comment]
The primary reason we haven't switched to `Path::Tiny` is that the `Path::Class` objects are exposed as part of the API. That said, I'd be in favor of switching with an appropriate warning in the `Changes` file and version bump.

Re: `Type::Tiny`, I agree there is concern about maintenance and I am not sure it gets us much since this distribution is already using `Moose`. If we were to switch type libraries, I might consider `Specio` as autarch is actively working on it these days, but I am inclined to stick with `MooseX::Types` for now.

**Comment by oalders** [comment]
Closing as there's no motivation to switch type checking right now.  Thanks for the suggestion @jjatria.

**Comment by jjatria** [comment]
No problem! :+1:
